[languages.d]
compile = "apt install ldc && ldc2 {path} --of={tempdir}/judge"
execute = "{tempdir}/judge"
bundle = "false"
list_dependencies = "sed 's/^import \\(.*\\);$/\\1/ ; t ; d' {path} | sed 's/\\./\\//g' | sed 's/^\\(.*\\)$/\\1.d/g'"
